apiVersion: v1
kind: ConfigMap
metadata:
  name: ngx-probe-cm

data:
  default.conf: |
    server {
      listen 80;
      location = /ready {
        return 200 'I am ready,developed by 付品欣';
      }
    }
